# Generated by Django 2.2.5 on 2019-09-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='date published')),
                ('twitter_id', models.IntegerField(default=0)),
                ('python_tip', models.CharField(max_length=280)),
                ('who_posted', models.CharField(max_length=50)),
            ],
        ),
    ]
